### ISSUE TITLE
gcc 4.8.1 build problem

### ISSUE THREAD

**Issue by kgodlewski** [t-mat/lz4mt#22]
This problem was introduced in 46c9ac79:

```
src/main.cpp: In constructor '{anonymous}::Option::Option(int, char**, std::string, std::string, std::string, {anonymous}::AttyFunc, {anonymous}::AttyFunc, {anonymous}::CmpFunc)':
src/main.cpp:174:2: warning: '{anonymous}::Option::replaceMap' should be initialized in the member initialization list [-Weffc++]
  Option(
  ^
src/main.cpp: In lambda function:
src/main.cpp:665:4: error: inconsistent types 'int (*)(const char*, char*, int, int, int)' and '{anonymous}::lz4mtCommandLine(int, char**)::__lambda8::__lambda9' deduced for lambda return type
    };
    ^
src/main.cpp:667:2: warning: control reaches end of non-void function [-Wreturn-type]
  }();
  ^
make: *** [obj/main.o] Error 1
```

GCC version: `gcc (Ubuntu 4.8.1-2ubuntu1~12.04) 4.8.1`

**Comment by t-mat** [comment]
Thanks for the report !
I'll investigate it.

**Comment by kgodlewski** [comment]
Great, thanks!

Here's a less cryptic message produced by clang:

```
src/main.cpp:663:4: error: return type '<lambda at src/main.cpp:663:11>' must match previous return type 'int (*)(const char *, char *, int, int, int)' when lambda expression has
      unspecified explicit return type
                        return [](const char* src, char* dst, int size, int maxOut, int) {
                        ^
1 error generated.
make: *** [obj/main.o] Error 1
```

**Comment by t-mat** [comment]
I've also confirmed compiling with `Mac OS / clang++ (Apple LLVM version 5.1, based on LLVM 3.4svn)`.
